// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqlQVwarfFA2qRC0U58C-_ZGa9K0sYku0',
    appId: '1:521924832535:web:62864a7a29c6fda3765b52',
    messagingSenderId: '521924832535',
    projectId: 'calmerbeats-e3cf1',
    authDomain: 'calmerbeats-e3cf1.firebaseapp.com',
    storageBucket: 'calmerbeats-e3cf1.appspot.com',
    measurementId: 'G-ZK0L4NJN7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDksHEBM5Jnt5JTCQK9sBBOT7aCjQEy5dI',
    appId: '1:521924832535:android:6360477ff269c65e765b52',
    messagingSenderId: '521924832535',
    projectId: 'calmerbeats-e3cf1',
    storageBucket: 'calmerbeats-e3cf1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX-PWTP51Ren-Fy5phF-gM8rrTDAZLA6E',
    appId: '1:521924832535:ios:c480432fbae50628765b52',
    messagingSenderId: '521924832535',
    projectId: 'calmerbeats-e3cf1',
    storageBucket: 'calmerbeats-e3cf1.appspot.com',
    iosBundleId: 'com.example.calmerBeats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX-PWTP51Ren-Fy5phF-gM8rrTDAZLA6E',
    appId: '1:521924832535:ios:c480432fbae50628765b52',
    messagingSenderId: '521924832535',
    projectId: 'calmerbeats-e3cf1',
    storageBucket: 'calmerbeats-e3cf1.appspot.com',
    iosBundleId: 'com.example.calmerBeats',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqlQVwarfFA2qRC0U58C-_ZGa9K0sYku0',
    appId: '1:521924832535:web:dc87b4dbafefdc78765b52',
    messagingSenderId: '521924832535',
    projectId: 'calmerbeats-e3cf1',
    authDomain: 'calmerbeats-e3cf1.firebaseapp.com',
    storageBucket: 'calmerbeats-e3cf1.appspot.com',
    measurementId: 'G-D3FK170MFL',
  );
}
